home:
  path: /
  defaults: {_controller: AppBundle:Default:index }

index:
    path: /user
    defaults: { _controller: AppBundle:User:index }

login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

logout:
    path: /logout
    defaults: { _controller: AppBundle:User:logout }
