home:
  path: /
  defaults: {_controller: AppBundle:Default:index }

login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

logout:
    path: /logout
    defaults: { _controller: AppBundle:User:logout }

password:
    path: /password_change
    defaults: { _controller: AppBundle:User:change }

list-article:
    path:     /article/list
    defaults: { _controller: AppBundle:Page:index }

edit-article:
    path:     /article/edit/{id}
    defaults: { _controller: AppBundle:Page:edit }
    requirements:
        page: '\d+'

new-article:
    path:     /article/new
    defaults: { _controller: AppBundle:Page:new }

delete-article:
    path:     /article/delete
    defaults: { _controller: AppBundle:Page:delete }
