home:
  path: /
  defaults: {_controller: AppBundle:Default:index }

login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

logout:
    path: /logout
    defaults: { _controller: AppBundle:User:logout }

password:
    path: /password_change
    defaults: { _controller: AppBundle:User:change }

list-article:
    path:     /article-list
    defaults: { _controller: AppBundle:Page:index }

edit-article:
    path:     /edit-article/{id}
    defaults: { _controller: AppBundle:Page:edit }
    requirements:
        page: '\d*'

delete-article:
    path:     /delete-article
    defaults: { _controller: AppBundle:Page:delete }
